<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Spider Translate - Bing</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px; vertical-align: central">
    <div id="header-logo" style="float: left">
        <b>Spider Bing com ZendFramework</b>
    </div>
</div>

<?php echo $this->layout()->content ?>

</body>
</html>