<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>Spider Translate - Bing</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <form action="" method="post" name="pt_en">
            <div>Português para Inglês</div>
            <div>
                <input type="text" name="pt"/>
                <br>
                <input type="text" name="en"/>
                <br>
                <input type="submit" value="Traduzir"/>
            </div>
        </form>
        <form action="" method="post" name="en_pt">
            <br>
            <br>
            <div>Inglês para Português</div>
            <div>
                <input type="text" name="pt"/>
                <br>
                <input type="text" name="en"/>
                <br>
                <input type="submit" value="Traduzir"/>
            </div>
        </form>
    </body>
</html>
